---
# tasks file for Nexus

# Install Docker (if not already installed)

- name: Pull Nexus Docker image
  community.docker.docker_image:  
    name: sonatype/nexus3
    tag: latest
    source: pull

- name: Run nexus container
  community.docker.docker_container:
    name: nexus
    image: sonatype/nexus3:latest
    state: started
    ports:
      - "8081:8081"
    restart_policy: on-failure
