---
# tasks file for docker-setup
- name: Ensure Python is installed
  raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
  changed_when: false

- name: Install apt dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

