---
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Python SDK
  ansible.builtin.pip:
    name: docker
    state: present
  become: yes

# - name: Pull SonarQube Docker image
#   community.docker.docker_image:
#     name: sonarqube
#     source: pull
#   become: yes

- name: Remove existing SonarQube container
  community.docker.docker_container:
    name: sonarqube
    state: absent
  become: yes

- name: Run SonarQube container
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:8.9-community  # Use an older, potentially less resource-intensive version
    state: started
    ports:
      - "9000:9000"
    restart_policy: on-failure
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
  become: yes